DROP TABLE IF EXISTS GENRE, FILMS, PLACE;

CREATE TABLE GENRE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR2(256)
);


CREATE TABLE FILMS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR2(256),
    GENRE_ID BIGINT REFERENCES GENRE(ID)
);


CREATE TABLE PLACE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR2(256),
    FILM_ID BIGINT REFERENCES FILMS(ID)
);

